export default {
  response: {
    game_count: 156,
    games: [
      {
        appid: 10,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 80,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 100,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 300,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 20,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 30,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 40,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 50,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 60,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 70,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 130,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 220,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 340,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 240,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 280,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 360,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 320,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 380,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 400,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 420,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 500,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 17410,
        playtime_forever: 172,
        playtime_windows_forever: 172,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 550,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 40800,
        playtime_forever: 168,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 620,
        playtime_forever: 20,
        playtime_windows_forever: 20,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 45760,
        playtime_forever: 2897,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 57900,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 113200,
        playtime_2weeks: 1,
        playtime_forever: 2782,
        playtime_windows_forever: 1,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 65300,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 211420,
        playtime_forever: 8,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 730,
        playtime_forever: 668,
        playtime_windows_forever: 77,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 200510,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 212680,
        playtime_forever: 727,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 219150,
        playtime_forever: 222,
        playtime_windows_forever: 222,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 220440,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 224760,
        playtime_forever: 93,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 241600,
        playtime_forever: 1162,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 35700,
        playtime_forever: 41,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 35720,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 39140,
        playtime_forever: 37,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 239350,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 238280,
        playtime_forever: 50,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 208610,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 245170,
        playtime_forever: 133,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 49520,
        playtime_forever: 948,
        playtime_windows_forever: 54,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 262060,
        playtime_forever: 303,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 235460,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 274230,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 274250,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 274290,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 289130,
        playtime_forever: 97,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 311690,
        playtime_forever: 320,
        playtime_windows_forever: 320,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 312670,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 247080,
        playtime_forever: 1197,
        playtime_windows_forever: 3,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 274170,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 257510,
        playtime_forever: 220,
        playtime_windows_forever: 220,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 250900,
        playtime_2weeks: 426,
        playtime_forever: 426,
        playtime_windows_forever: 426,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 304240,
        playtime_forever: 46,
        playtime_windows_forever: 46,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 297130,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 291650,
        playtime_forever: 580,
        playtime_windows_forever: 62,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 360740,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 361300,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 365660,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 274270,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 367520,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 219740,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 243970,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 322330,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 261570,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 387290,
        playtime_forever: 43,
        playtime_windows_forever: 43,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 391540,
        playtime_forever: 24,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 21690,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 221040,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 254700,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 423230,
        playtime_forever: 354,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 424370,
        playtime_forever: 1364,
        playtime_windows_forever: 1364,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 339340,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 268500,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 431240,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 431960,
        playtime_forever: 33,
        playtime_windows_forever: 33,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 453480,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 457140,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 281990,
        playtime_forever: 415,
        playtime_windows_forever: 415,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 461950,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 379720,
        playtime_forever: 197,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 489630,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 397060,
        playtime_forever: 354,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 292030,
        playtime_forever: 610,
        playtime_windows_forever: 94,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 7670,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 8850,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 8870,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 409710,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 409720,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 324800,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 418370,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 548430,
        playtime_forever: 152,
        playtime_windows_forever: 152,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 552590,
        playtime_forever: 36,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 553310,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 558420,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 588650,
        playtime_forever: 307,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 590590,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 606150,
        playtime_forever: 555,
        playtime_windows_forever: 555,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 619780,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 629090,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 632360,
        playtime_forever: 2596,
        playtime_windows_forever: 2596,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 632470,
        playtime_forever: 9,
        playtime_windows_forever: 9,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 678950,
        playtime_forever: 970,
        playtime_windows_forever: 747,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 414340,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 747350,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 704270,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 435150,
        playtime_2weeks: 19,
        playtime_forever: 220,
        playtime_windows_forever: 19,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 751780,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 765880,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 779290,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 782330,
        playtime_forever: 1240,
        playtime_windows_forever: 1240,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 788100,
        playtime_forever: 776,
        playtime_windows_forever: 776,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 812550,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 813630,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 824270,
        playtime_forever: 439,
        playtime_windows_forever: 439,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 828900,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 552500,
        playtime_forever: 500,
        playtime_windows_forever: 500,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 737010,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 846870,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 860950,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 861540,
        playtime_forever: 877,
        playtime_windows_forever: 0,
        playtime_mac_forever: 877,
        playtime_linux_forever: 0,
      },
      {
        appid: 883710,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 714010,
        playtime_forever: 65,
        playtime_windows_forever: 65,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 898650,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 905340,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 916730,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 919410,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 764790,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 945360,
        playtime_forever: 24,
        playtime_windows_forever: 24,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 583950,
        playtime_forever: 882,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 985890,
        playtime_forever: 343,
        playtime_windows_forever: 343,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 893180,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 994220,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 450390,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1020470,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1026420,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 814380,
        playtime_forever: 121,
        playtime_windows_forever: 121,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1096410,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1102190,
        playtime_forever: 1654,
        playtime_windows_forever: 1654,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1104660,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1142500,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 382560,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 703860,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1145360,
        playtime_2weeks: 3042,
        playtime_forever: 4609,
        playtime_windows_forever: 4609,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1209490,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1217060,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 310950,
        playtime_forever: 19,
        playtime_windows_forever: 19,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1090630,
        playtime_forever: 3884,
        playtime_windows_forever: 3884,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 1289310,
        playtime_forever: 56,
        playtime_windows_forever: 56,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 371140,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 579110,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
      {
        appid: 242700,
        playtime_forever: 0,
        playtime_windows_forever: 0,
        playtime_mac_forever: 0,
        playtime_linux_forever: 0,
      },
    ],
  },
}
